version: "3.0"
services:
  my_service:
          build : .
          image: rojasree/host-to-s3-backup
          container_name: s3uploader
          environment:
                - AWS_ACCESS_KEY_ID=xxxx
                - AWS_SECRET_ACCESS_KEY=xxxx
                - S3_BUCKET_URL=s3://s3upload-docker/
                - AWS_DEFAULT_REGION=us-east-1 #optional
                - BACKUP_NAME=filebackuup
          volumes:
                - /home/ubuntu/docker2s3backup/data:/data:ro #use ro to make sure the volume gets mounted read-only
          restart: always




